#
# Analyze repository with PSRule for Azure
#

# Note:
# This workflow is designed to run in templated repositories.

# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze Azure resources

# Run for main or PRs against main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    if: github.repository != 'Azure/PSRule.Rules.Azure-quickstart'
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@v1.11.0
      with:
        modules: 'PSRule.Rules.Azure'
