#
# Analyze repository with PSRule for Azure
#

# Note:
# This workflow is designed to run in templated repositories to check Azure Infrastructure as Code.

# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze Azure resources

# Run for main or PRs against main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    permissions:
      # actions: read
      contents: read
      # security-events: write
    if: github.repository != 'Azure/PSRule.Rules.Azure-quickstart'
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.Azure
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true

      # If you have GitHub Advanced Security you can upload PSRule scan results.
      # Uncomment the next step to use this feature.
      # - name: Upload results to security tab
      #   uses: github/codeql-action/upload-sarif@dd746615b3b9d728a6a37ca2045b68ca76d4841a # v3.28.8
      #   if: always()
      #   with:
      #     sarif_file: reports/ps-rule-results.sarif

      - name: Upload results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: PSRule-Sarif
          path: reports/ps-rule-results.sarif
          retention-days: 1
          if-no-files-found: error
