#
# Analyze repository with PSRule for Azure
#

# Note:
# This workflow is designed to run in templated repositories to check Azure Infrastructure as Code.

# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze Azure resources

# Run for main or PRs against main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    permissions:
      # actions: read
      contents: read
      # security-events: write
    if: github.repository != 'Azure/PSRule.Rules.Azure-quickstart'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Install a specific version of Bicep for consistency across CI runs.
      # - name: Install Bicep
      #   run: az bicep install --version v0.39.26
      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.Azure
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true
        # env:
        #   # Use Bicep from Azure CLI.
        #   PSRULE_AZURE_BICEP_USE_AZURE_CLI: true

      # If you have GitHub Advanced Security you can upload PSRule scan results.
      # Uncomment the next step to use this feature.
      # - name: Upload results to security tab
      #   uses: github/codeql-action/upload-sarif@dd746615b3b9d728a6a37ca2045b68ca76d4841a # v3.28.8
      #   if: always()
      #   with:
      #     sarif_file: reports/ps-rule-results.sarif

      - name: Upload results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: PSRule-Sarif
          path: reports/ps-rule-results.sarif
          retention-days: 1
          if-no-files-found: error
